# Dockerfile

# Use an official Elixir runtime as a parent image
FROM elixir:latest

# Set the working directory in the container
WORKDIR /

# Copy the current directory contents into the container at /usr/src/app
COPY . .

# Compile the Elixir app
RUN mix local.hex --force
RUN mix local.rebar --force
RUN elixirc app.exs

# Run app.exs when the container launches
ENTRYPOINT ["elixir", "app.exs"]
