# Dockerfile

# Use an official Python runtime as a parent image
FROM python:3.8-slim

# Set the working directory in the container
WORKDIR /

# Copy the current directory contents into the container at /usr/src/app
COPY . .

# No need to run pip install since there are no requirements
# RUN pip install --no-cache-dir -r requirements.txt

# Run app.py when the container launches
ENTRYPOINT ["python", "app.py"]
