# Usamos una imagen base de Python
FROM python:3.8-slim

# Establecemos el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copiamos los requisitos y los instalamos para nuestra aplicación
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copiamos el archivo de la aplicación al contenedor
COPY . .

# Exponemos el puerto que usará nuestra aplicación
EXPOSE 5000

# Definimos el volumen donde se almacenarán los registros
VOLUME /app/logs

# Ejecutamos nuestra aplicación
CMD ["python", "app.py"]
