apiVersion: apps/v1
kind: Deployment
metadata:
  name: node
spec:
  replicas: 2
  selector:
    matchLabels:   
      si3mshady: node
      
  template:
    metadata:
      labels:        
        si3mshady: node
    spec:
      containers:
      - name: node
        image:  si3mshady/slackclone-be:2
        ports:
        - containerPort: 9000
          hostPort: 9000

--- 
apiVersion: v1
kind: Service
metadata: 
  name: node
spec: 
  ports: 
    - port: 9000
      targetPort: 9000         
  selector: 
    si3mshady: node
  type: LoadBalancer
