apiVersion: apps/v1
kind: Deployment
metadata:
  name: reactfrontend
spec:
  replicas: 2
  selector:
    matchLabels:
      
      si3mshady: reactfrontend
    
  template:
    metadata:
      labels:
        
        si3mshady: reactfrontend
    spec:
      containers:
      - name: reactfrontend
        image: si3mshady/slackclone-fe:2 #1.2 uses intance ip addr instead of service name         
        ports:
        - containerPort: 80
          hostPort: 80

--- 
apiVersion: v1
kind: Service
metadata: 
  name: reactfrontend

spec: 
  ports: 
    - port: 80
      targetPort: 80     
    
  selector: 
    si3mshady: reactfrontend
  type: LoadBalancer